name: Setup Python + uv Environment

description: Reusable setup for Python projects using uv

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - name: Set up uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true

    - name: Sync dependencies
      shell: bash
      run: uv sync --all-groups
